week 7 assessment review answers
learn-academy-2023-alpha/week-7-assessment-JoshuaMaurer pull request #1
Opened 2023-04-04 23:34 UTC by JoshuaMaurer

# Submitting Week 7 Assessment

### ✅ Completed Files

Select the following as confirmation that the files in this repository are complete.

- [ ] Coding Challenges
- [ ] Coding Concepts
- [ ] Interview Questions

### 📝 Feedback

If you would like specific feedback on a particular problem please leave details here:

2023-04-04 23:43 UTC, JoshuaMaurer commented
GENE!!!!!!!!!!!!!!!!

2023-04-05 01:01 UTC, Genemichael25 requested changes
Hey Josh, I am requesting changes for the interview questions. I am not sure if you pushed up all your work but I can only see your answer for # 1 and it is blank for the rest. Let me know when you push up the rest so I can finish the review. Thanks

2023-04-05 01:01 UTC, Genemichael25 commented on code-challenges.test.js
> +    return array.map(({name, occupation}) => {
Awesome refactor! 💯

2023-04-05 01:01 UTC, Genemichael25 commented on code-challenges.test.js
> +        return array.filter(value => typeof value === 'number').map(number => number % 3)
Clean and extremely readable!!

2023-04-05 01:01 UTC, Genemichael25 commented on code-challenges.test.js
> +// Create a function called 'allTheSumsHaveBeenCubed' and pass an array through as the parameter. Using .reduce, which uses a below written callback function (** 3)  on every number in the array. It
I love this pseudocode and not just because like all the other functions, the naming is great, but very descriptive and why you choose to use certain syntax. 👏🏽

2023-04-05 01:01 UTC, Genemichael25 commented on code-challenges.test.js
> +// Tests:       3 passed, 3 total
Crushed it with the tests as well!

2023-04-10 15:04 UTC, Genemichael25 approved these changes
Outstanding work Josh!!! This was a great way to finish these off and it definitely displays a Competent level of comprehension. It is always a cool experience for me to see how the code evolves and the thought process as you look to refactor. From the tests setup, to the planning of the function and then the execution. awesome! 💯 Thank you for the effort you have put into these week after week. Keep up that work ethic as you look to LEARN new things and I am excited to see what you do next! 👏🏽

2023-04-10 15:04 UTC, Genemichael25 commented on interview-questions.md
> +
Great! Love the terminal commands you gave here with your answer.

2023-04-10 15:04 UTC, Genemichael25 commented on interview-questions.md
> +**/photos/:id	        DELETE	           destroy**
💯 Love the way you used a table for this one

2023-04-10 15:04 UTC, Genemichael25 commented on interview-questions.md
> +- Has verified all branches merged to main
Really went above and beyond with these stories. Planning is going to be big for capstone and this will certainly come in handy. Nicely done 👏🏽

2023-04-10 15:04 UTC, Genemichael25 commented on rails-commenting.rb
> +params here is again ensuring that the input data only contains the specific data that is in the strong params method below. It will then check if the data that is to be created in the updated databa
You may want to comment this out as well but it's not a big deal.

2023-04-10 15:04 UTC, Genemichael25 commented on rails-commenting.rb
> +    #  Inside of this strong params method, it is stating the request using the strong params will be permitted ONLY if it has a title as well and content attributes and that they are only permitted
You crushed this whole section 👏🏽

2023-04-10 15:13 UTC, merged